# Generated by Django 4.2.16 on 2024-11-13 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sector_assessment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, null=True)),
                ('max_time', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('max_questions', models.PositiveSmallIntegerField(default=30)),
                ('allowed_users', models.ManyToManyField(related_name='allowed_users', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(blank=True, max_length=512)),
                ('choice_image', models.ImageField(blank=True, null=True, upload_to=sector_assessment.models.get_image_file_path)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('question_text', models.TextField(blank=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to=sector_assessment.models.get_image_file_path)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sector_assessment.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sector_assessment.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='sector_assessment.question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='skills',
            field=models.ManyToManyField(to='core.skill'),
        ),
        migrations.CreateModel(
            name='AssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('question_counter', models.PositiveIntegerField(default=datetime.datetime(2024, 11, 13, 17, 11, 35, 31910, tzinfo=datetime.timezone.utc))),
                ('time_taken', models.DurationField(default=datetime.timedelta(0))),
                ('is_finished', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sector_assessment.assessment')),
                ('question_attempt', models.ManyToManyField(to='sector_assessment.questionattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assessment', 'user')},
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(to='sector_assessment.question'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_score', models.JSONField(default=None)),
                ('sector_score', models.JSONField(default=None)),
                ('assessment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sector_assessment.assessmentrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assessment_run', 'user')},
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='choice',
            order_with_respect_to='question',
        ),
    ]
